  [build]
  publish = "."  # Indique que les fichiers à publier sont à la racine du projet
  functions = "netlify/functions"  # Répertoire des fonctions

[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/posts"
  status = 200
  force = true


