backend:
  name: github
  repo: blog-test-site-assmat

  branch: main  # ou master, selon la branche principale de ton dépôt

media_folder: "images/uploads" # Où seront stockées les images
public_folder: "/images/uploads" # Le chemin pour accéder aux images depuis l'interface web

collections:
  - name: "posts" # Le nom de la collection (ici "posts")
    label: "Articles"
    folder: "_posts" # Le dossier où les fichiers seront créés
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Modèle du nom de fichier
    fields: # Les champs du formulaire CMS
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
